### ISSUE TITLE
Minimal privileges required for agent user

### ISSUE THREAD

**Issue by lfsm** [informix/informixhq-agent#5]
This is a request for the agent documentation:
What are the Informix privileges required by the users configured in the agent (either for the monitored Informix instance or for the repository database)?

I have setup a VM to test InformixHQ, but I am using the "informix" user for everything. How can I avoid using such a privileged user for the agent?

**Comment by ekuehnhausen** [comment]
The InformixHQ documentation was updated today and the required privileges can now be found in the Getting Started instructions for the agent (https://informix.github.io/informixhq-server/docs.html#starting-the-informixhq-agent) and in the InformixHQ Agent Configuration section (https://informix.github.io/informixhq-server/docs.html#informixhq-agent-configuration)

For the Informix instance being monitored (target.url), the user specified in the URL only requires CONNECT access to the sysmaster database.

For the repository database (repository.url), the user specified in the URL needs RESOURCE level permission on the database in order to be able to create tables.
